env:
    # browser: true
    es2021: true
    node: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:@typescript-eslint/eslint-recommended
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaVersion: latest
    sourceType: module
    project: './tsconfig.json'
plugins:
    - '@typescript-eslint'
rules: {}
overrides:
    - files:
          - '**/*/spec.ts'
      rules:
          '@typescript-eslint/no-non-null-assertion': off
          '@typescript-eslint/no-empty-functions': off
          '@typescript-eslint/no-unsafe-assignment': off
          '@typescript-eslint/no-var-requires': off
